[package]
name = "sensible-random-word-generator"
version = "0.1.0"
authors = ["Edvin Boul <kittenparry@users.noreply.github.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
Inflector = "0.11.4"
